{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "collabdocs.configMapName" . }}
  labels:
    {{- include "collabdocs.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
{{- end }}
