apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collabdocs.secretName" . }}
  labels:
    {{- include "collabdocs.labels" . | nindent 4 }}
data:
  db_url: {{ include "collabdocs.databaseUrl" . | b64enc | quote }}
  redis_url: {{ .Values.secrets.redisUrl | b64enc | quote }}
