apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ws-hpa
  labels:
    {{- include "collabdocs.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collabdocs-ws
  minReplicas: {{ .Values.websocket.hpa.minReplicas }}
  maxReplicas: {{ .Values.websocket.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.websocket.hpa.cpuUtilization }}
